name: iara_env
channels:
  - pyg
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda # Let conda resolve the local CUDA version automatically
  - pyg
  - pandas
  - scipy
  - pip:
    - prody
